<template>
  <header class="Header Header-blackShadow">
      <div class="Header__inner l-container--pc">
          <div class="Header__head"><a href="./"><img src="@/assets/images/common/logo-01.svg" alt="LINCRAFT" class="Header__head__img"></a></div>

          <button type="button" class="HamburgerMenu" id="HamburgerMenu_trigger"><span class="HamburgerMenu__body" id="HamburgerMenu"><span></span><span></span><span></span></span></button>

          <nav class="Nav" id="nav">
              <ul class="Nav__list">
                  <li class="Nav__item">
                      <a class="Nav__link" href="/#service">
                          <!-- Generated by IcoMoon.io -->
                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" class="Nav__icon">
                              <title>display</title>
                              <path d="M0 2v20h32v-20h-32zM30 20h-28v-16h28v16zM21 24h-10l-1 4-2 2h16l-2-2z"></path>
                          </svg>
                          SERVICE
                      </a>
                  </li>
                  <li class="Nav__item">
                      <a class="Nav__link" href="/#performance">
                          <!-- Generated by IcoMoon.io -->
                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" class="Nav__icon">
                              <title>wrench</title>
                              <path d="M31.342 25.559l-14.392-12.336c0.67-1.259 1.051-2.696 1.051-4.222 0-4.971-4.029-9-9-9-0.909 0-1.787 0.135-2.614 0.386l5.2 5.2c0.778 0.778 0.778 2.051 0 2.828l-3.172 3.172c-0.778 0.778-2.051 0.778-2.828 0l-5.2-5.2c-0.251 0.827-0.386 1.705-0.386 2.614 0 4.971 4.029 9 9 9 1.526 0 2.963-0.38 4.222-1.051l12.336 14.392c0.716 0.835 1.938 0.882 2.716 0.104l3.172-3.172c0.778-0.778 0.731-2-0.104-2.716z"></path>
                          </svg>
                          PERFORMANCE
                      </a>
                  </li>
                  <li class="Nav__item">
                      <a class="Nav__link" href="/#recruit">
                          <!-- Generated by IcoMoon.io -->
                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" class="Nav__icon">
                              <title>user-tie</title>
                              <path d="M10 6c0-3.314 2.686-6 6-6s6 2.686 6 6c0 3.314-2.686 6-6 6s-6-2.686-6-6zM24.002 14h-1.107l-6.222 12.633 2.327-11.633-3-3-3 3 2.327 11.633-6.222-12.633h-1.107c-3.998 0-3.998 2.687-3.998 6v10h24v-10c0-3.313 0-6-3.998-6z"></path>
                          </svg>
                          RECRUIT
                      </a>
                  </li>
                  <li class="Nav__item">
                      <a class="Nav__link" href="/#company">
                          <!--?xml version="1.0" encoding="utf-8"?-->
                          <!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                          <svg version="1.1" id="_x31_0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" xml:space="preserve" class="Nav__icon">
                          <g>
                          <path class="st0" d="M65.332,0H64.16l0,0H64v510.282v1.558l0,0V512h150.871V399.617h82.262V512H448V0H65.332z M327.687,114.086
                  h-40.961h-61.442H123.351h-0.465V71.488h102.398h61.442h40.961h21.902h39.535v42.598H349.59H327.687z M327.687,222.883h-40.961
                  h-61.442H122.886v-42.594h102.398h61.442h40.961h21.902h39.535v42.594H349.59H327.687z M389.125,289.086v42.598h-52.05h-9.387
                  h-40.961h-61.442H122.886v-42.598h102.398h61.442h40.961h9.387h51.836H389.125z"></path>
              </g>
              </svg>
                          COMPANY
                      </a>
                  </li>
                  <li class="Nav__item--contact">
                      <a class="Nav__link" href="/#contact">
                          <!-- Generated by IcoMoon.io -->
                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" class="Nav__icon">
                              <title>mail2</title>
                              <path d="M26.667 0h-21.333c-2.934 0-5.334 2.4-5.334 5.334v21.332c0 2.936 2.4 5.334 5.334 5.334h21.333c2.934 0 5.333-2.398 5.333-5.334v-21.332c0-2.934-2.399-5.334-5.333-5.334zM26.667 4c0.25 0 0.486 0.073 0.688 0.198l-11.355 9.388-11.355-9.387c0.202-0.125 0.439-0.198 0.689-0.198h21.333zM5.334 28c-0.060 0-0.119-0.005-0.178-0.013l7.051-9.78-0.914-0.914-7.293 7.293v-19.098l12 14.512 12-14.512v19.098l-7.293-7.293-0.914 0.914 7.051 9.78c-0.058 0.008-0.117 0.013-0.177 0.013h-21.333z"></path>
                          </svg>
                          CONTACT
                      </a>
                  </li>
              </ul>
          </nav>
          <!-- オーバーレイ -->
      </div>
  </header>
</template>

<script>
export default {
  name: 'Header'
}
</script>