name: s3-deploy-sample
on:
  push:
    branches: [s3]

jobs:
  UploadStaticFiles:
    name: Upload static files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: ./dist
        run: aws s3 sync . s3://s3.lincraft-dev.com --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"
